config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  root to: "books#index"
    get '/*a', to: 'application#not_found'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/unique_route.rb
class UniqueRoute < ApplicationRecord
searchkick
def search_data
{
dep_city_code: dep_city_code,
arr_city_code: arr_city_code,
arr_city_name: arr_city_name,
dep_city_name: dep_city_name,
weekly_flights_count: weekly_flights_count
}
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def not_found
    render json: { error: 'not_found' }
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,except: [:show]
  

  # GET /books
  # GET /books.json
  def index
    if params[:q].nil?
      @unique_routes = []
    else
      @unique_routes = UniqueRoute.search params[:q]
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @unique_routes = []
    else
      @unique_routes = UniqueRoute.search params[:q]
    end
  end
end

app/controllers/unique_routes_controller.rb
class UniqueRoutesController < ApplicationController

def index
	query = params[:q].presence || “*”
	@articles = UniqueRoute.search(query)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/unique_routes_helper.rb
module UniqueRoutesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if user_signed_in? %>
 <h2>  Currently You are log in as <b> <%= current_user.email %> </b></h2> 
  <%= link_to "Edit Profile", edit_user_registration_path%> <br/>
  <%= link_to "log out", destroy_user_session_path,method: :delete%>
<%else%>
 <li><%= link_to "Sign up", new_user_registration_path%></li>
 <li><%= link_to "Login", new_user_session_path%></li>
<%end%>



<h1>Unique routes Search</h1>

<%= form_for books_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
 
<table>
  <thead>
    <tr>
      <th>Departure City Code</th>
      <th>Arrival City Code</th>
      <th>Weekly Flights Count</th>
      <th>Distance</th>
      <th>HOP</th>
      <th>Departure City Name</th>
      <th>Arrival City Name</th>
      <th>Schedule Route Url</th>
      <th>Departure City Name AR</th>
      <th>Arrival City Name AR</th>
    </tr>
  </thead>
 
  <tbody>

    <% @unique_routes.each do |book| %>
      <tr>
        <td><%= book.dep_city_code %></td>
        <td><%= book.arr_city_code %></td>
        <td><%= book.weekly_flights_count %></td>
        <td><%= book.distance %></td>
        <td><%= book.hop %></td>
        <td><%= book.dep_city_name %></td>
        <td><%= book.arr_city_name %></td>
        <td><%= book.schedule_route_url %></td>
        <td><%= book.dep_city_name_ar %></td>
        <td><%= book.arr_city_name_ar %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<script>
</script>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>